steps:
    # Pull code from git
    - name: gcr.io/cloud-builders/git
      id: getRepo
      entrypoint: git
      args: ['clone', 'https://github.com/ashwin-athappan/node-app-gcp-deploy.git']
    # Build Docker image
    - name: gcr.io/cloud-builders/docker
      id: buildImage
      entrypoint: docker
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/server', './server']
    # Push Docker Image
    - name: gcr.io/cloud-builders/docker
      id: pushImage
      entrypoint: docker
      args: ['push', 'gcr.io/${PROJECT_ID}/server']
    # Configure cluster
    - name: 'gcr.io/cloud-builders/gcloud'
      id: configureCluster
      args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'simple-ci-cd	'
      - '--zone=us-central1-c'
    # Apply server-depl.yaml
    - name: 'gcr.io/cloud-builders/kubectl'
      id: applyServer
      args:
      - 'apply'
      - '-f'
      - './infra/k8s/server-depl.yaml'
    # Apply ingress.yaml
    - name: 'gcr.io/cloud-builders/kubectl'
      id: applyIngress
      args:
      - 'apply'
      - '-f'
      - './infra/k8s/ingress.yaml'
