steps:
    # Pull code from git
    - name: gcr.io/cloud-builders/git
      id: getRepo
      entrypoint: git
      args: ['clone', 'https://github.com/ashwin-athappan/node-app-gcp-deploy.git']
    # Build Docker image
    - name: gcr.io/cloud-builders/docker
      id: buildImage
      entrypoint: docker
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/server', './server']