steps:
    # Pull code from git
    - name: gcr.io/cloud-builders/git
      args: ['git', 'clone', 'https://github.com/ashwin-athappan/node-app-gcp-deploy.git']
      id: getRepo
      entrypoint: bash
    # Build Docker image
    - name: gcr.io/cloud-builders/docker
      args: ['docker', 'build', '-t', 'gcr.io/${PROJECT_ID}/server', './server']