steps:
    # Pull code from git
    - name: gcr.io/cloud-builders/git
      args: ['clone', '']
      id: getRepo
      entrypoint: bash
    - name: gcr.io/cloud-builders/docker
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/server', '.']